Repository yldio/asap-hub, pull requests merged in 2020-09, with the labels that each got.

#251 feat(user-menu): design amends
  apps/storybook/src/Icons.stories.tsx
  packages/react-components/src/icons/cross.tsx
  packages/react-components/src/icons/index.ts
  packages/react-components/src/icons/vertical-divider.tsx
  packages/react-components/src/molecules/MenuButton.tsx
  packages/react-components/src/molecules/UserMenuButton.tsx
  packages/react-components/src/molecules/__tests__/MenuButton.test.tsx
  packages/react-components/src/organisms/MenuHeader.tsx
  packages/react-components/src/organisms/UserNavigation.tsx
  packages/react-components/src/templates/Layout.tsx
  packages/react-components/src/templates/__tests__/Layout.test.tsx
Labels: frontend

#228 chore: clean asap-server api
  apps/asap-server/src/handlers/users/connect-by-code.ts
  apps/asap-server/src/handlers/users/fetch-by-code.ts
  apps/asap-server/src/handlers/users/fetch-me.ts
  apps/asap-server/test/handlers/users/connect-by-code.test.ts
  apps/asap-server/test/handlers/users/fetch-by-code.test.ts
  apps/asap-server/test/handlers/users/fetch-me.test.ts
  serverless.js
Labels: backend

#229 chore: merge auth0 rules
  .pnp.js
  apps/auth0-add-user-metadata/.eslintrc.js
  apps/auth0-add-user-metadata/README.md
  apps/auth0-connect-user/babel.config.js
  apps/auth0-connect-user/package.json
  apps/auth0-connect-user/tsconfig.json
  apps/auth0-rules/.eslintrc.js
  apps/auth0-rules/README.md
  apps/auth0-rules/babel.config.js
  apps/auth0-rules/package.json
  apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
  apps/auth0-rules/src/__tests__/connect-user.test.ts
  apps/auth0-rules/src/add-user-metadata.ts
  apps/auth0-rules/src/connect-user.ts
  apps/auth0-rules/tsconfig.json
  docs/config/auth0.md
  yarn.lock
Labels: backend

#248 manual cleanup buckets
  ci/s3-clean-buckets.sh
Labels: backend

#252 feat(user-menu): show user's teams
  apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
  apps/auth0-rules/src/add-user-metadata.ts
  apps/frontend/src/App.tsx
  packages/auth/src/index.ts
  packages/react-components/src/auth-test-utils.tsx
  packages/react-context/src/__tests__/auth.test.tsx
Labels: frontend

#253 Feat: Search Field
  apps/storybook/src/Icons.stories.tsx
  apps/storybook/src/SearchField.stories.tsx
  packages/react-components/src/atoms/TextField.tsx
  packages/react-components/src/atoms/__tests__/TextField.test.tsx
  packages/react-components/src/icons/index.ts
  packages/react-components/src/icons/search-icon.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/molecules/SearchField.tsx
  packages/react-components/src/molecules/__tests__/SearchField.test.tsx
  packages/react-components/src/molecules/index.ts
Labels: frontend

#247 Feat: Toggle
  apps/storybook/src/Icons.stories.tsx
  apps/storybook/src/Toggle.stories.tsx
  packages/react-components/src/atoms/Toggle.tsx
  packages/react-components/src/atoms/__tests__/Toggle.test.tsx
  packages/react-components/src/atoms/index.ts
  packages/react-components/src/icons/team.tsx
  packages/react-components/src/icons/user.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/theme.ts
Labels: frontend

#263 feat(profile, team): outputs coming soon placeholder
  apps/frontend/src/teams/Team.tsx
  apps/frontend/src/teams/__tests__/Team.test.tsx
  apps/frontend/src/users/Profile.tsx
  apps/storybook/src/ComingSoon.stories.tsx
  apps/storybook/src/ProfilePage.stories.tsx
  apps/storybook/src/Tag.stories.tsx
  apps/storybook/src/TeamPage.stories.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/organisms/ComingSoon.tsx
  packages/react-components/src/organisms/__tests__/ComingSoon.test.tsx
  packages/react-components/src/organisms/index.ts
  packages/react-components/src/templates/ProfileOutputs.tsx
  packages/react-components/src/templates/TeamHeader.tsx
  packages/react-components/src/templates/TeamOutputs.tsx
  packages/react-components/src/templates/__tests__/ProfileOutputs.test.tsx
  packages/react-components/src/templates/__tests__/TeamOutputs.test.tsx
  packages/react-components/src/templates/__tests__/TeamPage.test.tsx
  packages/react-components/src/templates/index.ts
Labels: frontend

#258 Feat: Network page header
  apps/frontend/src/App.tsx
  apps/frontend/src/fixtures/teams.ts
  apps/frontend/src/fixtures/users.ts
  apps/frontend/src/network/Profile.tsx
  apps/frontend/src/network/ProfileList.tsx
  apps/frontend/src/network/Routes.tsx
  apps/frontend/src/network/Team.tsx
  apps/frontend/src/network/TeamList.tsx
  apps/frontend/src/network/__tests__/Profile.test.tsx
  apps/frontend/src/network/__tests__/ProfileList.test.tsx
  apps/frontend/src/network/__tests__/Routes.test.tsx
  apps/frontend/src/network/__tests__/Team.test.tsx
  apps/frontend/src/network/__tests__/TeamList.test.tsx
  apps/frontend/src/teams/Routes.tsx
  apps/frontend/src/users/Routes.tsx
  apps/storybook/src/NetworkHeader.stories.tsx
  apps/storybook/src/NetworkPage.stories.tsx
  packages/react-components/src/atoms/Toggle.tsx
  packages/react-components/src/organisms/MembersSection.tsx
  packages/react-components/src/organisms/ProfileBackground.tsx
  packages/react-components/src/organisms/__tests__/ProfileBackground.test.tsx
  packages/react-components/src/templates/NetworkPage.tsx
  packages/react-components/src/templates/NetworkPageHeader.tsx
  packages/react-components/src/templates/__tests__/NetworkPage.test.tsx
  packages/react-components/src/templates/__tests__/NetworkPageHeader.test.tsx
Labels: frontend

#265 Fix: People design amends
  apps/storybook/src/Card.stories.tsx
  packages/react-components/src/atoms/Card.tsx
  packages/react-components/src/atoms/GlobalStyles.tsx
  packages/react-components/src/atoms/Paragraph.tsx
  packages/react-components/src/atoms/__tests__/Card.test.tsx
  packages/react-components/src/molecules/ProfilePersonalText.tsx
  packages/react-components/src/organisms/PeopleCard.tsx
Labels: frontend

#266 Misc styling changes
  packages/react-components/src/atoms/Button.tsx
  packages/react-components/src/atoms/TextField.tsx
  packages/react-components/src/atoms/Toggle.tsx
  packages/react-components/src/atoms/__tests__/TextField.test.tsx
  packages/react-components/src/form.ts
  packages/react-components/src/icons/filter-icon.tsx
  packages/react-components/src/icons/search-icon.tsx
  packages/react-components/src/templates/NetworkPageHeader.tsx
Labels: frontend

#284 chore: type squidex search query
  packages/services-common/src/squidex/index.ts
  packages/services-common/test/squidex/squidex.test.ts
Labels: backend

#281 Feat: Rich text error handling
  apps/storybook/src/RichText.stories.tsx
  packages/react-components/src/atoms/index.ts
  packages/react-components/src/icons/cross.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/molecules/RichTextError.tsx
  packages/react-components/src/molecules/index.ts
  packages/react-components/src/organisms/RichText.tsx
  packages/react-components/src/organisms/__tests__/RichText.test.tsx
  packages/react-components/src/organisms/index.ts
  packages/react-components/src/templates/ContentPage.tsx
Labels: frontend

#290 chore: separate webhooks
  apps/asap-server/src/handlers/webhooks/cronjob-sync-orcid.ts
  apps/asap-server/src/handlers/webhooks/webhook-connect-by-code.ts
  apps/asap-server/src/handlers/webhooks/webhook-fetch-by-code.ts
  apps/asap-server/src/handlers/webhooks/webhook-sync-orcid.ts
  apps/asap-server/src/utils/validate-squidex-request.ts
  apps/asap-server/test/handlers/webhooks/cronjob-sync-orcid.test.ts
  apps/asap-server/test/handlers/webhooks/webhook-connect.test.ts
  apps/asap-server/test/handlers/webhooks/webhook-fetch-by-code.test.ts
  apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.test.ts
  apps/asap-server/test/helpers/create-squidex-signature.ts
  serverless.js
Labels: backend

#257 feat: add text and type to outputs
  apps/asap-server/src/controllers/research-outputs.ts
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/src/entities/research-outputs.ts
  apps/asap-server/src/entities/team.ts
  apps/asap-server/test/handlers/research-outputs/fetch-by-id.test.ts
  apps/asap-server/test/handlers/research-outputs/fetch.test.ts
  apps/asap-server/test/handlers/users/fetch-by-id.test.ts
  apps/frontend/src/api/research-outputs.ts
  apps/frontend/src/research-outputs/ResearchOutput.tsx
  apps/storybook/src/ResearchOutputPage.stories.tsx
  packages/model/src/research-output.ts
  packages/react-components/src/atoms/TagLabel.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/templates/ResearchOutputPage.tsx
  packages/react-components/src/templates/__tests__/ResearchOutputPage.test.tsx
  packages/react-components/src/templates/index.ts
Labels: backend, frontend

#295 feat: adds teams pagination, refactors tests
  apps/asap-server/src/cms/index.ts
  apps/asap-server/src/cms/teams.ts
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/src/entities/user.ts
  apps/asap-server/src/handlers/teams/fetch.ts
  apps/asap-server/test/handlers/content/fetch-by-slug.test.ts
  apps/asap-server/test/handlers/research-outputs/create.test.ts
  apps/asap-server/test/handlers/research-outputs/fetch-by-id.test.ts
  apps/asap-server/test/handlers/research-outputs/fetch.test.ts
  apps/asap-server/test/handlers/teams/fetch-by-id.test.ts
  apps/asap-server/test/handlers/teams/fetch.fixtures.ts
  apps/asap-server/test/handlers/teams/fetch.test.ts
  apps/asap-server/test/handlers/teams/integration.test.ts
  apps/asap-server/test/handlers/users/fetch-by-id.test.ts
  apps/asap-server/test/handlers/users/fetch.test.ts
  apps/asap-server/test/handlers/users/integration.test.ts
  apps/asap-server/test/handlers/webhooks/cronjob-sync-orcid.test.ts
  apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.test.ts
  apps/asap-server/test/helpers/squidex.ts
  apps/asap-server/test/helpers/teams.ts
  apps/frontend/src/api/teams.ts
  apps/frontend/src/fixtures/teams.ts
  apps/frontend/src/network/TeamList.tsx
  apps/frontend/src/network/__tests__/TeamList.test.tsx
  jest-base.config.js
  packages/model/src/team.ts
Labels: backend

#303 fix: fetch only 10 orcid works
  apps/asap-server/src/controllers/users.ts
  apps/asap-server/test/fixtures/fetch-orcid-works-0000-0002-9079-593X.json
  apps/asap-server/test/fixtures/mjff-sample.csv
  apps/asap-server/test/fixtures/users.fetch-with-orcid-sorted.json
  apps/asap-server/test/fixtures/users.orcid-works-deserialised.json
  apps/asap-server/test/handlers/webhooks/cronjob-sync-orcid.fixtures.ts
  apps/asap-server/test/handlers/webhooks/cronjob-sync-orcid.test.ts
  apps/asap-server/test/handlers/webhooks/fetch-orcid-works.fixtures.json
  apps/asap-server/test/handlers/webhooks/users-create-squidex-webhook.fixtures.json
  apps/asap-server/test/handlers/webhooks/users-update-squidex-webhook.fixtures.json
  apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.test.ts
  apps/storybook/src/ProfilePage.stories.tsx
  apps/storybook/src/ProfileRecentWorks.stories.tsx
  packages/model/src/user.ts
  packages/react-components/src/organisms/__tests__/ProfileRecentWorks.test.tsx
Labels: backend
