Repository yldio/asap-hub, pull requests merged in 2020-11, with the labels that each got.

#428 feat: adds update team endpoint
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/src/entities/team.ts
  apps/asap-server/src/handlers/teams/update.ts
  apps/asap-server/test/handlers/teams/update.test.ts
  packages/squidex/src/squidex.ts
  packages/squidex/test/patch.test.ts
  serverless.js
Labels: backend

#433 Fix: Change link
  apps/frontend/src/App.tsx
Labels: frontend

#426 feat: adjust import properties
  apps/asap-cli/src/import/insert.ts
  apps/asap-cli/src/import/parse-data.ts
  apps/asap-cli/src/invite/index.ts
  apps/asap-cli/test/import.test.ts
  apps/asap-cli/test/invite.test.ts
  apps/asap-cli/test/user-membership.fixture.csv
Labels: frontend

#435 feat: change copy to shared help section
  apps/frontend/src/network/profile/__tests__/Routes.test.tsx
  packages/react-components/src/templates/ProfileStaff.tsx
Labels: frontend

#416 Feat: Modal
  apps/frontend/src/network/team/Routes.tsx
  apps/frontend/src/network/team/__tests__/Routes.test.tsx
  apps/storybook/src/Modal.stories.tsx
  apps/storybook/src/TeamPage.stories.tsx
  apps/storybook/src/ToolCard.stories.tsx
  packages/react-components/src/atoms/Label.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/molecules/Modal.tsx
  packages/react-components/src/molecules/ModalEditHeader.tsx
  packages/react-components/src/molecules/__tests__/Modal.test.tsx
  packages/react-components/src/molecules/__tests__/ModalEditHeader.test.tsx
  packages/react-components/src/molecules/index.ts
  packages/react-components/src/organisms/LinkCard.tsx
  packages/react-components/src/organisms/ToolCard.tsx
  packages/react-components/src/organisms/ToolModal.tsx
  packages/react-components/src/organisms/__tests__/ToolCard.test.tsx
  packages/react-components/src/organisms/__tests__/ToolModal.test.tsx
  packages/react-components/src/organisms/index.ts
  packages/react-components/src/templates/ForgotPasswordPage.tsx
  packages/react-components/src/templates/InviteUserForm.tsx
  packages/react-components/src/templates/RecordOutputForm.tsx
  packages/react-components/src/templates/SigninForm.tsx
  packages/react-components/src/templates/TeamHeader.tsx
  packages/react-components/src/templates/TeamWorkspace.tsx
  packages/react-components/src/templates/__tests__/TeamHeader.test.tsx
  packages/react-components/src/templates/__tests__/TeamWorkspace.test.tsx
Labels: frontend

#437 filter hidden profiles
  apps/asap-server/src/controllers/users.ts
  apps/asap-server/test/handlers/users/fetch.test.ts
Labels: backend

#438 fix: add team members to patch response
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/test/handlers/teams/update.test.ts
Labels: backend

#430 feat(profile-page): edit buttons in tabs
  apps/storybook/src/ProfilePage.stories.tsx
  apps/storybook/src/SharedResearchCard.stories.tsx
  apps/storybook/src/SharedResearchHeader.stories.tsx
  apps/storybook/src/SharedResearchPage.stories.tsx
  packages/react-components/src/browser-test-utils.tsx
  packages/react-components/src/organisms/ProfileCardList.tsx
  packages/react-components/src/organisms/ResultList.tsx
  packages/react-components/src/organisms/__tests__/ProfileCardList.browser-test.tsx
  packages/react-components/src/organisms/__tests__/ProfileCardList.test.tsx
  packages/react-components/src/organisms/__tests__/ResultList.test.tsx
  packages/react-components/src/organisms/index.ts
  packages/react-components/src/templates/NetworkPeople.tsx
  packages/react-components/src/templates/NetworkTeams.tsx
  packages/react-components/src/templates/NewsAndEventsPageBody.tsx
  packages/react-components/src/templates/ProfileAbout.tsx
  packages/react-components/src/templates/ProfileOutputs.tsx
  packages/react-components/src/templates/ProfilePage.tsx
  packages/react-components/src/templates/ProfileResearch.tsx
  packages/react-components/src/templates/ProfileStaff.tsx
  packages/react-components/src/templates/SharedResearchPageBody.tsx
  packages/react-components/src/templates/__tests__/ProfileAbout.test.tsx
  packages/react-components/src/templates/__tests__/ProfileHeader.browser-test.tsx
  packages/react-components/src/templates/__tests__/ProfileHeader.test.tsx
  packages/react-components/src/templates/__tests__/ProfileResearch.test.tsx
Labels: frontend

#439 fix: adds user orcidworks to response
  apps/asap-server/src/entities/user.ts
  apps/asap-server/test/handlers/discover/fetch.test.ts
  apps/asap-server/test/handlers/users/fetch.fixtures.ts
  packages/squidex/src/entities/user.ts
Labels: backend

#440 Tools Persist
  apps/frontend/src/api/__tests__/use-safe-fetch.test.tsx
  apps/frontend/src/api/__tests__/util.test.tsx
  apps/frontend/src/api/util.ts
  apps/frontend/src/network/team/Routes.tsx
  apps/frontend/src/network/team/__tests__/Routes.test.tsx
  apps/frontend/src/news/__tests__/Routes.test.tsx
  packages/react-components/src/organisms/ToolModal.tsx
  packages/react-components/src/organisms/__tests__/ToolModal.test.tsx
Labels: frontend

#427 feat: change team roles
  apps/asap-cli/src/import/insert.ts
  apps/asap-cli/test/import.test.ts
  apps/asap-cli/test/user-membership.fixture.csv
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/test/handlers/teams/fetch.fixtures.ts
  apps/asap-server/test/handlers/users/fetch.fixtures.ts
  apps/asap-server/test/handlers/users/fetch.test.ts
  apps/asap-server/test/handlers/users/update.fixtures.ts
  apps/asap-server/test/helpers/users.ts
  apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
  apps/frontend/src/dashboard/__tests__/Dashboard.test.tsx
  apps/frontend/src/fixtures/teams.ts
  apps/frontend/src/fixtures/users.ts
  apps/frontend/src/network/__tests__/Routes.test.tsx
  apps/storybook/src/MembersSection.stories.tsx
  apps/storybook/src/NetworkPage.stories.tsx
  apps/storybook/src/TeamPage.stories.tsx
  packages/fixtures/src/teams.ts
  packages/model/src/team.ts
  packages/model/src/user.ts
  packages/react-components/src/auth-test-utils.tsx
  packages/react-components/src/molecules/__tests__/ProfilePersonalText.test.tsx
  packages/react-components/src/organisms/__tests__/MembersSections.test.tsx
  packages/react-components/src/organisms/__tests__/PeopleCard.test.tsx
  packages/react-components/src/organisms/__tests__/ProfileBackground.test.tsx
  packages/react-components/src/organisms/__tests__/TeamCard.test.tsx
  packages/react-components/src/templates/NetworkPageHeader.tsx
  packages/react-components/src/templates/__tests__/NetworkPeople.test.tsx
  packages/react-components/src/templates/__tests__/ProfileResearch.test.tsx
  packages/react-components/src/templates/__tests__/TeamHeader.test.tsx
  packages/squidex/schema/schemas/users.json
  packages/squidex/src/entities/user.ts
Labels: backend, frontend

#454 feat: allows removal of user attributes
  apps/asap-server/src/controllers/users.ts
  apps/asap-server/src/entities/user.ts
  apps/asap-server/test/handlers/users/update.fixtures.ts
  apps/asap-server/test/handlers/users/update.test.ts
  packages/model/src/user.ts
  packages/squidex/src/entities/user.ts
  packages/squidex/src/squidex.ts
Labels: backend

#459 remove user displayname
  apps/asap-cli/src/import/insert.ts
  apps/asap-cli/test/import.test.ts
  apps/asap-cli/test/invite.fixtures.ts
  apps/asap-server/src/controllers/discover.ts
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/src/controllers/users.ts
  apps/asap-server/src/entities/user.ts
  apps/asap-server/src/handlers/users/create.ts
  apps/asap-server/test/handlers/discover/fetch.test.ts
  apps/asap-server/test/handlers/teams/fetch.fixtures.ts
  apps/asap-server/test/handlers/users/create.test.ts
  apps/asap-server/test/handlers/users/fetch.fixtures.ts
  apps/asap-server/test/handlers/users/fetch.test.ts
  apps/asap-server/test/handlers/users/update.fixtures.ts
  apps/asap-server/test/handlers/users/update.test.ts
  apps/asap-server/test/handlers/webhooks/cronjob-sync-orcid.fixtures.ts
  apps/asap-server/test/handlers/webhooks/webhook-connect.test.ts
  apps/asap-server/test/handlers/webhooks/webhook-fetch-by-code.fixtures.ts
  apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.fixtures.ts
  apps/asap-server/test/helpers/users.ts
  apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
  apps/frontend/src/App.tsx
  apps/frontend/src/admin/Admin.tsx
  apps/frontend/src/admin/__tests__/Admin.test.tsx
  apps/frontend/src/fixtures/teams.ts
  apps/frontend/src/fixtures/users.ts
  apps/storybook/src/AdminInviteUserPage.stories.tsx
  apps/storybook/src/InviteUserForm.stories.tsx
  packages/model/src/user.ts
  packages/react-components/src/index.ts
  packages/react-components/src/organisms/__tests__/PeopleCard.test.tsx
  packages/react-components/src/templates/AdminInviteUserPage.tsx
  packages/react-components/src/templates/InviteUserForm.tsx
  packages/react-components/src/templates/__tests__/AdminInviteUserPage.test.tsx
  packages/react-components/src/templates/__tests__/InviteUserForm.test.tsx
  packages/react-components/src/templates/__tests__/ProfilePage.test.tsx
  packages/react-components/src/templates/index.ts
  packages/react-context/src/__tests__/auth.test.tsx
  packages/squidex/src/entities/user.ts
  serverless.js
Labels: backend, frontend

#465 feat: add edit user teams
  apps/asap-server/src/controllers/users.ts
  apps/asap-server/src/entities/user.ts
  apps/asap-server/src/handlers/users/update.ts
  apps/asap-server/src/utils/__mocks__/validate-token.ts
  apps/asap-server/test/handlers/users/update.fixtures.ts
  apps/asap-server/test/handlers/users/update.test.ts
  packages/model/src/user.ts
Labels: backend

#477 fix: prevent null from propagating to the FE
  apps/asap-server/src/entities/user.ts
  apps/asap-server/test/handlers/users/update.fixtures.ts
  apps/asap-server/test/handlers/users/update.test.ts
Labels: backend

#478 fix: graphQL transformer
  apps/asap-server/src/entities/user.ts
  apps/asap-server/test/handlers/users/fetch.fixtures.ts
  packages/squidex/src/entities/user.ts
Labels: backend

#490 feat: adds outputs to team response :yolo:
  apps/asap-cli/src/import/insert.ts
  apps/asap-cli/test/import.fixtures.ts
  apps/asap-server/src/controllers/teams.ts
  apps/asap-server/src/entities/research-output.ts
  apps/asap-server/src/entities/team.ts
  apps/asap-server/test/handlers/teams/fetch-by-id.fixtures.ts
  apps/asap-server/test/handlers/teams/fetch-by-id.test.ts
  apps/asap-server/test/handlers/teams/fetch.fixtures.ts
  apps/asap-server/test/handlers/teams/fetch.test.ts
  apps/asap-server/test/handlers/teams/update.fixtures.ts
  apps/asap-server/test/handlers/teams/update.test.ts
  apps/asap-server/test/handlers/users/fetch.fixtures.ts
  apps/asap-server/test/handlers/users/fetch.test.ts
  apps/asap-server/test/helpers/teams.ts
  apps/frontend/src/fixtures/teams.ts
  apps/frontend/src/network/teams/TeamProfile.tsx
  apps/storybook/src/TeamProfilePage.stories.tsx
  packages/fixtures/src/teams.ts
  packages/model/src/team.ts
  packages/react-components/src/organisms/SharedResearchCard.tsx
  packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
  packages/react-components/src/templates/TeamProfileOutputs.tsx
  packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
  packages/react-components/src/templates/__tests__/TeamProfilePage.test.tsx
  packages/squidex/src/entities/common.ts
  packages/squidex/src/entities/team.ts
Labels: backend, frontend

#487 Feat: Proposal Search
  apps/asap-server/src/controllers/research-outputs.ts
  apps/asap-server/src/entities/research-output.ts
  apps/asap-server/src/handlers/research-outputs/fetch.ts
  apps/asap-server/test/handlers/research-outputs/fetch.test.ts
  packages/model/src/research-output.ts
  packages/react-components/src/organisms/SharedResearchCard.tsx
  packages/react-components/src/templates/SharedResearchPageHeader.tsx
Labels: backend, frontend
